apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
#opaque is the generic type of secret for the (coredentilas)
type: Opaque  
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: admin123
