apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: three-tier-eks
  region: ap-south-1

managedNodeGroups:

  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3

    volumeSize: 30
    volumeType: gp3

    iam:
      withAddonPolicies:
        ebs: true
