apiVersion: v1
kind: Pod
metadata:
  name: secret-subpath
spec:
  containers:
    - name: toolbox
      image: qamre/toolbox:v1
      volumeMounts:
        - name: db-secret
          mountPath: /etc/app/secret-password
          subPath: password

  volumes:
    - name: db-secret
      secret:
        secretName: db-credentials
        defaultMode: 0400
