apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order
      image: qamre/order-service:v1

      env:
        - name: INVENTORY_URL
          valueFrom:
            configMapKeyRef:
              name: order-config
              key: INVENTORY_URL