apiVersion: v1
kind: Pod
metadata:
  name: config-subpath
spec:
  containers:
    - name: toolbox
      image: qamre/toolbox:v1
      volumeMounts:
        - name: app-config
          mountPath: /etc/app/name.txt
          subPath: APP_NAME
  volumes:
    - name: app-config
      configMap:
        name: app-config
