apiVersion: v1
kind: Pod
metadata:
  name: config-inspector
  labels:
    app: inventory
spec:
  containers:
    - name: toolbox
      image: qamre/inventory-service:v3
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
      volumeMounts:
        - name: app-config
          mountPath: /etc/app/config
  volumes:
    - name: app-config
      configMap:
        name: app-config
