apiVersion: v1
kind: Pod
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  containers:
    - name: inventory-service
      image: qamre/inventory-service:v3
      ports:
        - containerPort: 5678
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/app/config

  volumes:
    - name: app-config-volume
      configMap:
        name: app-config
