apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: common-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/poc7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: common-storage
  resources:
    requests:
      storage: 1Gi
