apiVersion: v1
kind: Pod
metadata:
  name: pod00
  labels:
    app: cloudethix-k8s-00 
spec:
  nodeSelector:
    node-name: cloudethix-k8s-00
  containers:
    - name: nginx
      image: nginx:latest
