apiVersion: v1
kind: Pod
metadata:
  name: cloudethix-k8s-00
spec:
  nodeName: minikube-m02
  containers:
  - name: nginx
    image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: cloudethix-k8s-01
spec:
  nodeName: minikube-m03
  containers:
  - name: nginx
    image: nginx:latest
