apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: cloudethix-k8s-00
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: pod-a
      image: nginx:latest
      ports:
        - containerPort: 80
