apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: cloudethix-k8s-01
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: pod-b
      image: nginx:latest
      ports:
        - containerPort: 80
