apiVersion: v1
kind: Pod
metadata:
  name: secret-inspector
spec:
  containers:
    - name: secret-inspector
      image: qamre/toolbox:v1
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
      volumeMounts:
        - name: db-secrets
          mountPath: /etc/app/secrets
  volumes:
    - name: db-secrets
      secret:
        secretName: db-credentials
