apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
          volumeMounts:
            - name: exports
              mountPath: /exports
      volumes:
        - name: exports
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: poc
spec:
  type: ClusterIP
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP

