apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: poc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi

